#pragma once
#include <QString>
#include <QDateTime>
#include <QFileInfo>

namespace M1 {

/// Represents a single media item in the Mcaster1Studio media library.
/// Maps to the `media_items` table in the MariaDB database.
struct MediaItem {
    qint64    id           = 0;
    QString   filePath;
    QString   title;
    QString   artist;
    QString   albumArtist;
    QString   album;
    QString   genre;
    QString   year;
    QString   trackNumber;
    QString   composer;
    QString   comment;
    QString   isrc;
    QString   mbid;         ///< MusicBrainz recording ID
    QString   label;
    QString   language;

    double    bpm          = 0.0;
    QString   musicalKey;   ///< e.g. "Am", "Gmaj"
    int       durationMs   = 0;
    int       bitrate      = 0;
    int       sampleRate   = 44100;
    int       channels     = 2;
    QString   codec;        ///< "mp3", "flac", "ogg", "opus", "wav", "aac"
    qint64    fileSize     = 0;

    // Library management
    int       rating       = 0;     ///< 0-5 stars
    double    energy       = 0.0;   ///< 0.0-1.0 energy level
    double    weight       = 1.0;   ///< Rotation weight
    QString   mood;
    QString   tags;                 ///< Comma-separated custom tags
    bool      explicit_    = false; ///< Explicit content flag

    // AutoDJ
    int       autoDjWeight    = 50;  ///< 0-100: 0=never, 50=normal, 100=always-prefer
    int       autoDjSkipCount = 0;   ///< Times user skipped this track in AutoDJ

    // Album art
    bool      hasArt         = false; ///< Embedded artwork detected during scan

    // Timestamps
    QDateTime dateAdded;
    QDateTime dateModified;
    QDateTime lastPlayed;
    int       playCount    = 0;

    // Waveform cache (path to .waveform file, generated by engine)
    QString   waveformCache;

    // Helper
    QString displayTitle() const {
        return title.isEmpty() ? QFileInfo(filePath).completeBaseName() : title;
    }
    QString displayArtist() const {
        return albumArtist.isEmpty() ? artist : albumArtist;
    }
    QString durationString() const {
        int s = durationMs / 1000;
        return QString("%1:%2").arg(s / 60).arg(s % 60, 2, 10, QChar('0'));
    }
};

} // namespace M1

// Make MediaItem usable in Qt containers
#include <QMetaType>
Q_DECLARE_METATYPE(M1::MediaItem)
