# cmake/version.cmake
# Version information for Mcaster1Studio
# Included by root CMakeLists.txt via configure_file

set(MCASTER1STUDIO_VERSION_MAJOR 0)
set(MCASTER1STUDIO_VERSION_MINOR 1)
set(MCASTER1STUDIO_VERSION_PATCH 0)
set(MCASTER1STUDIO_VERSION_TWEAK 0)
set(MCASTER1STUDIO_VERSION "${MCASTER1STUDIO_VERSION_MAJOR}.${MCASTER1STUDIO_VERSION_MINOR}.${MCASTER1STUDIO_VERSION_PATCH}")
set(MCASTER1STUDIO_VERSION_STRING "0.1.0-alpha")
set(MCASTER1STUDIO_BUILD_DATE "2026-03-02")
